name: Compile Examples
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - STMicroelectronics:stm32:Nucleo_64:pnum=NUCLEO_L476RG
          # - STMicroelectronics:stm32:Disco:pnum=B_U585I_IOT02A
          # - STMicroelectronics:stm32:Disco:pnum=STM32WB5MM_DK

    steps:
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - source-url: https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json
              name: STMicroelectronics:stm32
